# Generated by Django 2.1.3 on 2020-09-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('머신러닝', '머신러닝'), ('파이썬', '파이썬'), ('알고리즘', '알고리즘')], max_length=80, verbose_name='분야')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('author', models.CharField(max_length=100, verbose_name='작성자')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('image', models.ImageField(blank=True, null=True, upload_to='studyGroups/image/', verbose_name='이미지')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
        ),
    ]
